- name: Java Build VM
  hosts: localhost
  remote_user: ec2-user
  become: true

  tasks:
    - name: Install dependencies
      ansible.builtin.yum:
        name: "{{ package }}"
        state: present
      vars:
        package:
          - git
          - tree

    - name: Install and configure Docker
      block:
        - name: Install Docker
          ansible.builtin.package:
            name: docker
            state: latest

        - name: Ensure group "docker" exists
          ansible.builtin.group:
            name: docker
            state: present

        - name: Add ec2-user user to docker group
          ansible.builtin.user:
            name: ec2-user
            group: docker
            append: true

        - name: Start Docker service
          ansible.builtin.service:
            name: docker
            state: started
            enabled: true

        - name: Change permissions of docker.sock
          ansible.builtin.file:
            path: "/var/run/docker.sock"
            state: file
            mode: "0777"

    - name: Install and configure Maven
      block:
        - name: Download and Unarchive maven
          ansible.builtin.unarchive:
            src: https://downloads.apache.org/maven/maven-3/3.9.12/binaries/apache-maven-3.9.12-bin.tar.gz
            dest: /opt
            remote_src: true

        - name: Create maven symlink to /usr/bin
          ansible.builtin.file:
            src: /opt/apache-maven-3.9.12/bin/mvn
            dest: /usr/bin/mvn
            state: link

        - name: Configure maven and its environment variables
          ansible.builtin.lineinfile:
            dest: "/etc/profile.d/maven.sh"
            line: "{{ item.line }}"
            create: true
            state: present
            mode: "0644"
          with_items:
            - { line: "M2_HOME=/opt/apache-maven-3.9.12" }
            - { line: "PATH=$PATH:$M2_HOME/bin" }
